services:
  db:
    image: postgres:latest
    domainname: ${POSTGRES_SERVER:-db}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  projects:
    build:
      context: ./projects
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
volumes:
  db-data:
