"""Init migration

Revision ID: 000000000000
Revises:
Create Date: 2025-01-11 00:00:00.000000

"""

# revision identifiers, used by Alembic
revision = "000000000000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
